# Generated by Django 4.2.3 on 2024-02-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='Volunteer',
            new_name='volunteer',
        ),
        migrations.AddField(
            model_name='donation',
            name='donationarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.donationarea'),
        ),
        migrations.AddField(
            model_name='donation',
            name='volunteerremark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Food Donation', 'Food Donation'), ('Cloth Donation', 'Cloth Donation'), ('Footwear Donation', 'Footwear Donation'), ('Books Donation', 'Books Donation'), ('Furniture Donation', 'Furniture Donation'), ('Vessel Donation', 'Vessel Donation'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
